In [1]:
# Question 1: What is MongoDB? Explain non-relational databases in short. In which scenarios it is preferred to use MongoDB over SQL databases?

# Answer :

# MongoDB is a popular open-source NoSQL database system that stores data in a document-oriented format. Instead of using tables and rows like in traditional relational databases, MongoDB stores data in documents that are organized into collections. These documents can contain a variety of data types, such as arrays and nested documents, and can be easily updated and queried.These documents are stored in bson (binary JSON) format.

# Non-relational databases, also known as NoSQL databases, are databases that do not use the traditional table-based relational database model. Instead, they use different data models, such as key-value, document-oriented, or graph-based, to store and organize data. Non-relational databases are often used for handling large amounts of unstructured or semi-structured data, and they can be more flexible and scalable than traditional SQL databases.

# MongoDB is preferred over SQL databases in scenarios where:

# Flexibility and scalability are important: MongoDB is designed to be flexible and scalable, making it a good choice for handling large and complex data sets.

# Agile development: MongoDB's flexible schema allows for more agile and iterative development, as changes can be made to the database schema without requiring a complete redesign of the application.

# Big Data and real-time analytics: MongoDB is well-suited for big data and real-time analytics, as it can easily handle unstructured and semi-structured data.

# Cloud-based applications: MongoDB is often used for cloud-based applications, as it can easily scale to meet the demands of a growing user base.

# Geospatial data: MongoDB has built-in support for geospatial data, making it a popular choice for applications that involve location-based services.

In [2]:
# Question 2: State and Explain the features of MongoDB.
    
# Answer :
    
# In MongoDB, data is organized into a hierarchy of databases, collections, and documents.

# A database is a container for a set of collections, each with its own set of documents. In MongoDB, you can have multiple databases within a single MongoDB server instance.

# A collection is a group of MongoDB documents, similar to a table in a relational database. Collections are used to group related documents together and typically have a common schema, although MongoDB's flexible document model allows for some variation within a collection. Each collection within a MongoDB database is given a unique name that is used to identify and access the collection.

# A document is a set of key-value pairs that is stored within a collection. In MongoDB, a document is similar to a record in a relational database, but it is stored in a flexible and dynamic format known as BSON (Binary JSON). Each document can have its own unique structure and can include nested sub-documents and arrays.

# MongoDB Hierarchy

# These are some important features of MongoDB:

# Support ad hoc queries - In MongoDB, you can search by field, range query and it also supports regular expression searches.

# Indexing - You can index any field in a document.

# Replication - MongoDB supports Master Slave replication. A master can perform Reads and Writes and a Slave copies data from the master and can only be used for reads or back up (not writes)

# Duplication of data - MongoDB can run over multiple servers. The data is duplicated to keep the system up and also keep its running condition in case of hardware failure.

# Load balancing - It has an automatic load balancing configuration because of data placed in shards.

# Supports map reduce and aggregation tools.

# Uses JavaScript instead of Procedures.

# It is a schema-less database written in C++.

# Provides high performance.

# Stores files of any size easily without complicating your stack.

# Easy to administer in the case of failures.

# It also supports:

# JSON data model with dynamic schemas
# Auto-sharding for horizontal scalability
# Built in replication for high availability

In [3]:
# Question 3: Write a code to connect MongoDB to Python. Also, create a database and a collection in MongoDB.
# Answer :
# 1. Installing pymongo

In [4]:
%pip install pymongo

Requirement already satisfied: pymongo in c:\users\ram charan reddy\anaconda3\lib\site-packages (4.6.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\users\ram charan reddy\anaconda3\lib\site-packages (from pymongo) (2.5.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pymongo


client = pymongo.MongoClient("mongodb+srv://ramc53112:ramc53112@cluster0.rxufn56.mongodb.net/?retryWrites=true&w=majority")


mydb = client["mydatabase"]


mycol = mydb["customers"]


data = [
  { "name": "John", "address": "Highway 37" },
  { "name": "Peter", "address": "Lowstreet 27" },
  { "name": "Amy", "address": "Apple st 652" },
  { "name": "Hannah", "address": "Mountain 21" },
  { "name": "Michael", "address": "Valley 345" },
  { "name": "Sandy", "address": "Ocean blvd 2" },
  { "name": "Betty", "address": "Green Grass 1" },
  { "name": "Richard", "address": "Sky st 331" },
  { "name": "Susan", "address": "One way 98" },
  { "name": "Vicky", "address": "Yellow Garden 2" },
  { "name": "Ben", "address": "Park Lane 38" },
  { "name": "William", "address": "Central st 954" },
  { "name": "Chuck", "address": "Main Road 989" },
  { "name": "Viola", "address": "Sideway 1633" }
]


mycol.insert_many(data)


print(client.list_database_names())


print(mydb.list_collection_names())

['Ramc53112', 'mydatabase', 'admin', 'local']
['customers']

In [7]:
#Q4. Using the database and the collection created in question number 3, write a code to insert one record,
#and insert many records. Use the find() and find_one() methods to print the inserted record.

In [8]:
import pymongo


client = pymongo.MongoClient("mongodb+srv://ramc53112:ramc53112@cluster0.rxufn56.mongodb.net/?retryWrites=true&w=majority")


mydb = client["mydatabase"]
mycol = mydb["customers"]


one_record = { "name": "Alice", "address": "123 Elm Street" }
mycol.insert_one(one_record)


many_records = [
    { "name": "Bob", "address": "456 Oak Avenue" },
    { "name": "Carol", "address": "789 Maple Drive" },
    { "name": "David", "address": "101 Pine Road" }
]
mycol.insert_many(many_records)


print("Inserted Records using find() method:")
for record in mycol.find():
    print(record)


print("\nFirst Inserted Record using find_one() method:")
print(mycol.find_one())

Inserted Records using find() method:
{'_id': ObjectId('65cb87117c5a6a390cda752e'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('65cb87117c5a6a390cda752f'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('65cb87117c5a6a390cda7530'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('65cb87117c5a6a390cda7531'), 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': ObjectId('65cb87117c5a6a390cda7532'), 'name': 'Michael', 'address': 'Valley 345'}
{'_id': ObjectId('65cb87117c5a6a390cda7533'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('65cb87117c5a6a390cda7534'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('65cb87117c5a6a390cda7535'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('65cb87117c5a6a390cda7536'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('65cb87117c5a6a390cda7537'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('65cb87117c5a6a390cda7538'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('65cb87117c5a6a390cda7539'), 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('65cb87117c5a6a390cda753a'), 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': ObjectId('65cb87117c5a6a390cda753b'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('65cb88367c5a6a390cda753d'), 'name': 'Alice', 'address': '123 Elm Street'}
{'_id': ObjectId('65cb88377c5a6a390cda753e'), 'name': 'Bob', 'address': '456 Oak Avenue'}
{'_id': ObjectId('65cb88377c5a6a390cda753f'), 'name': 'Carol', 'address': '789 Maple Drive'}
{'_id': ObjectId('65cb88377c5a6a390cda7540'), 'name': 'David', 'address': '101 Pine Road'}

First Inserted Record using find_one() method:
{'_id': ObjectId('65cb87117c5a6a390cda752e'), 'name': 'John', 'address': 'Highway 37'}

In [9]:
#Q5. Explain how you can use the find() method to query the MongoDB database. Write a simple code to
#demonstrate this.

In [10]:

#In MongoDB, the find() method is used to query a collection and retrieve documents that match specified criteria. This method allows you to filter documents based on specific conditions and retrieve the results. Here's how you can use the find() method:

#Basic Query: You can pass an empty document {} to the find() method to retrieve all documents in the collection.

#Query with Conditions: You can specify conditions using a document with key-value pairs. MongoDB will return documents that match these conditions.

#Projection: You can specify which fields you want to include or exclude from the result set using projection. This helps in reducing the size of the returned documents.

#Sorting: You can sort the results based on one or more fields in ascending or descending order.

import pymongo


client = pymongo.MongoClient("mongodb+srv://ramc53112:ramc53112@cluster0.rxufn56.mongodb.net/?retryWrites=true&w=majority")


mydb = client["mydatabase"]
mycol = mydb["customers"]


data = [
    { "name": "John", "age": 30 },
    { "name": "Alice", "age": 25 },
    { "name": "Bob", "age": 35 },
    { "name": "Carol", "age": 40 }
]
mycol.insert_many(data)


print("All documents in the collection:")
for document in mycol.find():
    print(document)


print("\nDocuments with age greater than 30:")
for document in mycol.find({ "age": { "$gt": 30 } }):
    print(document)


print("\nName of all documents:")
for document in mycol.find({}, { "_id": 0, "name": 1 }):
    print(document)


print("\nDocuments sorted by age in descending order:")
for document in mycol.find().sort("age", pymongo.DESCENDING):
    print(document)

All documents in the collection:
{'_id': ObjectId('65cb87117c5a6a390cda752e'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('65cb87117c5a6a390cda752f'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('65cb87117c5a6a390cda7530'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('65cb87117c5a6a390cda7531'), 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': ObjectId('65cb87117c5a6a390cda7532'), 'name': 'Michael', 'address': 'Valley 345'}
{'_id': ObjectId('65cb87117c5a6a390cda7533'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('65cb87117c5a6a390cda7534'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('65cb87117c5a6a390cda7535'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('65cb87117c5a6a390cda7536'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('65cb87117c5a6a390cda7537'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('65cb87117c5a6a390cda7538'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('65cb87117c5a6a390cda7539'), 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('65cb87117c5a6a390cda753a'), 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': ObjectId('65cb87117c5a6a390cda753b'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('65cb88367c5a6a390cda753d'), 'name': 'Alice', 'address': '123 Elm Street'}
{'_id': ObjectId('65cb88377c5a6a390cda753e'), 'name': 'Bob', 'address': '456 Oak Avenue'}
{'_id': ObjectId('65cb88377c5a6a390cda753f'), 'name': 'Carol', 'address': '789 Maple Drive'}
{'_id': ObjectId('65cb88377c5a6a390cda7540'), 'name': 'David', 'address': '101 Pine Road'}
{'_id': ObjectId('65cb88be7c5a6a390cda7542'), 'name': 'John', 'age': 30}
{'_id': ObjectId('65cb88be7c5a6a390cda7543'), 'name': 'Alice', 'age': 25}
{'_id': ObjectId('65cb88be7c5a6a390cda7544'), 'name': 'Bob', 'age': 35}
{'_id': ObjectId('65cb88be7c5a6a390cda7545'), 'name': 'Carol', 'age': 40}

Documents with age greater than 30:
{'_id': ObjectId('65cb88be7c5a6a390cda7544'), 'name': 'Bob', 'age': 35}
{'_id': ObjectId('65cb88be7c5a6a390cda7545'), 'name': 'Carol', 'age': 40}

Name of all documents:
{'name': 'John'}
{'name': 'Peter'}
{'name': 'Amy'}
{'name': 'Hannah'}
{'name': 'Michael'}
{'name': 'Sandy'}
{'name': 'Betty'}
{'name': 'Richard'}
{'name': 'Susan'}
{'name': 'Vicky'}
{'name': 'Ben'}
{'name': 'William'}
{'name': 'Chuck'}
{'name': 'Viola'}
{'name': 'Alice'}
{'name': 'Bob'}
{'name': 'Carol'}
{'name': 'David'}
{'name': 'John'}
{'name': 'Alice'}
{'name': 'Bob'}
{'name': 'Carol'}

Documents sorted by age in descending order:
{'_id': ObjectId('65cb88be7c5a6a390cda7545'), 'name': 'Carol', 'age': 40}
{'_id': ObjectId('65cb88be7c5a6a390cda7544'), 'name': 'Bob', 'age': 35}
{'_id': ObjectId('65cb88be7c5a6a390cda7542'), 'name': 'John', 'age': 30}
{'_id': ObjectId('65cb88be7c5a6a390cda7543'), 'name': 'Alice', 'age': 25}
{'_id': ObjectId('65cb87117c5a6a390cda752e'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('65cb87117c5a6a390cda752f'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('65cb87117c5a6a390cda7530'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('65cb87117c5a6a390cda7531'), 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': ObjectId('65cb87117c5a6a390cda7532'), 'name': 'Michael', 'address': 'Valley 345'}
{'_id': ObjectId('65cb87117c5a6a390cda7533'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('65cb87117c5a6a390cda7534'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('65cb87117c5a6a390cda7535'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('65cb87117c5a6a390cda7536'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('65cb87117c5a6a390cda7537'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('65cb87117c5a6a390cda7538'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('65cb87117c5a6a390cda7539'), 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('65cb87117c5a6a390cda753a'), 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': ObjectId('65cb87117c5a6a390cda753b'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('65cb88367c5a6a390cda753d'), 'name': 'Alice', 'address': '123 Elm Street'}
{'_id': ObjectId('65cb88377c5a6a390cda753e'), 'name': 'Bob', 'address': '456 Oak Avenue'}
{'_id': ObjectId('65cb88377c5a6a390cda753f'), 'name': 'Carol', 'address': '789 Maple Drive'}
{'_id': ObjectId('65cb88377c5a6a390cda7540'), 'name': 'David', 'address': '101 Pine Road'}

In [11]:
# Q6. Explain the sort() method. Give an example to demonstrate sorting in MongoDB.

#Answer:

# In MongoDB, the sort() method is used to specify the order in which the query results should be returned. This method allows you to sort the documents returned by a query based on one or more fields, either in ascending or descending order.

# The sort() method takes a document as an argument, where each field you want to sort by is a key, and the value of the key determines the sort order. If the value is 1, the field will be sorted in ascending order, and if the value is -1, the field will be sorted in descending order.

In [12]:
import pymongo


client = pymongo.MongoClient("mongodb+srv://ramc53112:ramc53112@cluster0.rxufn56.mongodb.net/?retryWrites=true&w=majority")


mydb = client["mydatabase"]
mycol = mydb["customers"]


data = [
    { "name": "John", "age": 30 },
    { "name": "Alice", "age": 25 },
    { "name": "Bob", "age": 35 },
    { "name": "Carol", "age": 40 }
]
mycol.insert_many(data)


print("Documents sorted by age in ascending order:")
for document in mycol.find().sort("age", pymongo.ASCENDING):
    print(document)


print("\nDocuments sorted by age in descending order:")
for document in mycol.find().sort("age", pymongo.DESCENDING):
    print(document)

Documents sorted by age in ascending order:
{'_id': ObjectId('65cb87117c5a6a390cda752e'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('65cb87117c5a6a390cda752f'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('65cb87117c5a6a390cda7530'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('65cb87117c5a6a390cda7531'), 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': ObjectId('65cb87117c5a6a390cda7532'), 'name': 'Michael', 'address': 'Valley 345'}
{'_id': ObjectId('65cb87117c5a6a390cda7533'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('65cb87117c5a6a390cda7534'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('65cb87117c5a6a390cda7535'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('65cb87117c5a6a390cda7536'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('65cb87117c5a6a390cda7537'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('65cb87117c5a6a390cda7538'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('65cb87117c5a6a390cda7539'), 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('65cb87117c5a6a390cda753a'), 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': ObjectId('65cb87117c5a6a390cda753b'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('65cb88367c5a6a390cda753d'), 'name': 'Alice', 'address': '123 Elm Street'}
{'_id': ObjectId('65cb88377c5a6a390cda753e'), 'name': 'Bob', 'address': '456 Oak Avenue'}
{'_id': ObjectId('65cb88377c5a6a390cda753f'), 'name': 'Carol', 'address': '789 Maple Drive'}
{'_id': ObjectId('65cb88377c5a6a390cda7540'), 'name': 'David', 'address': '101 Pine Road'}
{'_id': ObjectId('65cb88be7c5a6a390cda7543'), 'name': 'Alice', 'age': 25}
{'_id': ObjectId('65cb894f7c5a6a390cda7548'), 'name': 'Alice', 'age': 25}
{'_id': ObjectId('65cb88be7c5a6a390cda7542'), 'name': 'John', 'age': 30}
{'_id': ObjectId('65cb894f7c5a6a390cda7547'), 'name': 'John', 'age': 30}
{'_id': ObjectId('65cb88be7c5a6a390cda7544'), 'name': 'Bob', 'age': 35}
{'_id': ObjectId('65cb894f7c5a6a390cda7549'), 'name': 'Bob', 'age': 35}
{'_id': ObjectId('65cb88be7c5a6a390cda7545'), 'name': 'Carol', 'age': 40}
{'_id': ObjectId('65cb894f7c5a6a390cda754a'), 'name': 'Carol', 'age': 40}

Documents sorted by age in descending order:
{'_id': ObjectId('65cb88be7c5a6a390cda7545'), 'name': 'Carol', 'age': 40}
{'_id': ObjectId('65cb894f7c5a6a390cda754a'), 'name': 'Carol', 'age': 40}
{'_id': ObjectId('65cb88be7c5a6a390cda7544'), 'name': 'Bob', 'age': 35}
{'_id': ObjectId('65cb894f7c5a6a390cda7549'), 'name': 'Bob', 'age': 35}
{'_id': ObjectId('65cb88be7c5a6a390cda7542'), 'name': 'John', 'age': 30}
{'_id': ObjectId('65cb894f7c5a6a390cda7547'), 'name': 'John', 'age': 30}
{'_id': ObjectId('65cb88be7c5a6a390cda7543'), 'name': 'Alice', 'age': 25}
{'_id': ObjectId('65cb894f7c5a6a390cda7548'), 'name': 'Alice', 'age': 25}
{'_id': ObjectId('65cb87117c5a6a390cda752e'), 'name': 'John', 'address': 'Highway 37'}
{'_id': ObjectId('65cb87117c5a6a390cda752f'), 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': ObjectId('65cb87117c5a6a390cda7530'), 'name': 'Amy', 'address': 'Apple st 652'}
{'_id': ObjectId('65cb87117c5a6a390cda7531'), 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': ObjectId('65cb87117c5a6a390cda7532'), 'name': 'Michael', 'address': 'Valley 345'}
{'_id': ObjectId('65cb87117c5a6a390cda7533'), 'name': 'Sandy', 'address': 'Ocean blvd 2'}
{'_id': ObjectId('65cb87117c5a6a390cda7534'), 'name': 'Betty', 'address': 'Green Grass 1'}
{'_id': ObjectId('65cb87117c5a6a390cda7535'), 'name': 'Richard', 'address': 'Sky st 331'}
{'_id': ObjectId('65cb87117c5a6a390cda7536'), 'name': 'Susan', 'address': 'One way 98'}
{'_id': ObjectId('65cb87117c5a6a390cda7537'), 'name': 'Vicky', 'address': 'Yellow Garden 2'}
{'_id': ObjectId('65cb87117c5a6a390cda7538'), 'name': 'Ben', 'address': 'Park Lane 38'}
{'_id': ObjectId('65cb87117c5a6a390cda7539'), 'name': 'William', 'address': 'Central st 954'}
{'_id': ObjectId('65cb87117c5a6a390cda753a'), 'name': 'Chuck', 'address': 'Main Road 989'}
{'_id': ObjectId('65cb87117c5a6a390cda753b'), 'name': 'Viola', 'address': 'Sideway 1633'}
{'_id': ObjectId('65cb88367c5a6a390cda753d'), 'name': 'Alice', 'address': '123 Elm Street'}
{'_id': ObjectId('65cb88377c5a6a390cda753e'), 'name': 'Bob', 'address': '456 Oak Avenue'}
{'_id': ObjectId('65cb88377c5a6a390cda753f'), 'name': 'Carol', 'address': '789 Maple Drive'}
{'_id': ObjectId('65cb88377c5a6a390cda7540'), 'name': 'David', 'address': '101 Pine Road'}

In [13]:
#Q7. Explain why delete_one(), delete_many(), and drop() is used.

In [ ]:
#Answer
# In MongoDB, delete_one(), delete_many(), and drop() are used for different purposes related to removing data or collections from the database.

# delete_one():

# This method is used to delete a single document that matches the specified criteria.
# It takes a filter document as a parameter, which specifies the criteria for matching the document to be deleted.
# If multiple documents match the filter, only the first one encountered will be deleted.
# It is typically used when you want to remove a specific document from a collection.
# delete_many():

# This method is used to delete multiple documents that match the specified criteria.
# It takes a filter document as a parameter, similar to delete_one(), specifying the criteria for matching documents to be deleted.
# All documents that match the filter will be deleted.
# It is useful when you want to remove multiple documents from a collection based on certain criteria.
# drop():

# This method is used to drop an entire collection from the database.
# It does not take any parameters.
# Dropping a collection removes all documents within that collection and the collection itself.
# It is typically used when you want to completely remove a collection and all its data from the database.
# These methods provide flexibility in managing data within MongoDB collections:

# delete_one() and delete_many() allow for targeted removal of specific documents or groups of documents based on specified criteria.
# drop() provides a way to remove an entire collection and its contents in one operation.
# It's essential to use these methods carefully, especially drop(), as it permanently removes data from the database and cannot be undone. Always ensure you're deleting the correct data or collection to avoid unintended data loss.